version: '3.8'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver Community
    networks:
      - bridge
    restart: unless-stopped

networks:
  bridge:
