version: '3.8'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver Community
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - bridge
    restart: unless-stopped

volumes:
  cloudbeaver_data:

networks:
  bridge:
