version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    network_mode: "host"
    restart: always
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:
