version: '3.8'

services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - bridge
    restart: unless-stopped

volumes:
  redisinsight_data:

networks:
  bridge:
