version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis_semanainfo
    command: >
      redis-server
      --requirepass <senha>
      --user semanainfouser on >qSLxPOm7Dkd9Nw4 ~* +@all
    volumes:
      - redis_data:/data
    networks:
      - banco
    restart: always 

volumes:
  redis_data:

networks:
  banco:
    driver: bridge

